<a href="https://colab.research.google.com/github/DVN111/How-to-Scraping-Data-with-BeautifulSoup-in-Python/blob/main/How_to_Scraping_Data_from_Website.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from bs4 import BeautifulSoup
import requests

In [2]:
url="https://en.wikipedia.org/wiki/List_of_largest_companies_in_Indonesia"
page = requests.get(url)

In [3]:
soup = BeautifulSoup(page.text,'html')

In [4]:
table = soup.find_all('table', class_= 'wikitable sortable')[1]

In [5]:
table_headers = table.findAll('th')

In [6]:
list_header = [header.text.strip() for header in table_headers]

In [7]:
import pandas as pd
df = pd.DataFrame(columns=list_header)

In [8]:
df

Empty DataFrame
Columns: [Rank, Forbes 2000 rank, Name, Headquarters, Revenue(billions US$), Profit(billions US$), Assets(billions US$), Value(billions US$), Industry]
Index: []

In [9]:
column_data = table.findAll('tr')
print(column_data
)

[<tr>
<th align="center">Rank
</th>
<th align="center">Forbes <br/>2000 rank
</th>
<th align="center">Name
</th>
<th align="center">Headquarters
</th>
<th align="center">Revenue<br/>(billions <br/>US$)
</th>
<th align="center">Profit<br/>(billions <br/>US$)
</th>
<th align="center">Assets<br/>(billions <br/>US$)
</th>
<th align="center">Value<br/>(billions <br/>US$)
</th>
<th align="center">Industry
</th></tr>, <tr>
<td>1
</td>
<td>350
</td>
<td align="left"><a href="/wiki/Bank_Rakyat_Indonesia" title="Bank Rakyat Indonesia">Bank Rakyat Indonesia</a>
</td>
<td align="left"><a href="/wiki/Jakarta" title="Jakarta">Jakarta</a>
</td>
<td>12.8
</td>
<td>2.2
</td>
<td>117.7
</td>
<td>50.1
</td>
<td align="left"><a class="mw-redirect" href="/wiki/Banking_industry" title="Banking industry">Banking</a>
</td></tr>, <tr>
<td>2
</td>
<td>489
</td>
<td align="left"><a href="/wiki/Bank_Mandiri" title="Bank Mandiri">Bank Mandiri</a>
</td>
<td align="left">Jakarta
</td>
<td>9.5
</td>
<td>2
</td>
<td>121.1
</td>
<td>26.9
</td>
<td align="left">Banking
</td></tr>, <tr>
<td>3
</td>
<td>517
</td>
<td align="left"><a href="/wiki/Bank_Central_Asia" title="Bank Central Asia">Bank Central Asia</a>
</td>
<td align="left">Jakarta
</td>
<td>6.1
</td>
<td>2.3
</td>
<td>87.7
</td>
<td>67.6
</td>
<td align="left">Banking
</td></tr>, <tr>
<td>4
</td>
<td>745
</td>
<td align="left"><a href="/wiki/Telkom_Indonesia" title="Telkom Indonesia">Telkom Indonesia</a>
</td>
<td align="left"><a href="/wiki/Bandung" title="Bandung">Bandung</a>
</td>
<td>10
</td>
<td>1.7
</td>
<td>19.5
</td>
<td>31.9
</td>
<td align="left"><a class="mw-redirect" href="/wiki/Telecommunication" title="Telecommunication">Telecommunication</a>
</td></tr>, <tr>
<td>5
</td>
<td>1153
</td>
<td align="left"><a href="/wiki/Bank_Negara_Indonesia" title="Bank Negara Indonesia">Bank Negara Indonesia</a>
</td>
<td align="left">Jakarta
</td>
<td>4.8
</td>
<td>.8
</td>
<td>67.7
</td>
<td>12.1
</td>
<td align="left">Banking
</td></tr>, <tr>
<td>6
</td>
<td>1749
</td>
<td align="left"><a class="new" href="/w/index.php?title=Bayan_Resources&amp;action=edit&amp;redlink=1" title="Bayan Resources (page does not exist)">Bayan Resources</a>
</td>
<td align="left">Jakarta
</td>
<td>2.9
</td>
<td>1.2
</td>
<td>2.4
</td>
<td>9.8
</td>
<td align="left"><a href="/wiki/Coal_mining" title="Coal mining">Coal mining</a>
</td></tr>, <tr>
<td>7
</td>
<td>1867
</td>
<td align="left"><a class="new" href="/w/index.php?title=Saratoga_Investama_Sedaya&amp;action=edit&amp;redlink=1" title="Saratoga Investama Sedaya (page does not exist)">Saratoga Investama Sedaya</a>
</td>
<td align="left">Jakarta
</td>
<td>.12
</td>
<td>1.7
</td>
<td>4.3
</td>
<td>3.4
</td>
<td align="left"><a href="/wiki/Holding_company" title="Holding company">Holding company</a>
</td></tr>]

In [10]:
for row in column_data[1:]:
  row_data = row.findAll('td') # row data akan menyimpan data
  ind_row_data = [data.text.strip() for data in row_data]

  #masukkan data untuk tiap cell keadalam df
  length = len(df)
  df.loc[length] = ind_row_data

In [11]:
df

,Rank,Forbes 2000 rank,Name,Headquarters,Revenue(billions US$),Profit(billions US$),Assets(billions US$),Value(billions US$),Industry
0,1,350,Bank Rakyat Indonesia,Jakarta,12.8,2.2,117.7,50.1,Banking
1,2,489,Bank Mandiri,Jakarta,9.5,2,121.1,26.9,Banking
2,3,517,Bank Central Asia,Jakarta,6.1,2.3,87.7,67.6,Banking
3,4,745,Telkom Indonesia,Bandung,10,1.7,19.5,31.9,Telecommunication
4,5,1153,Bank Negara Indonesia,Jakarta,4.8,.8,67.7,12.1,Banking
5,6,1749,Bayan Resources,Jakarta,2.9,1.2,2.4,9.8,Coal mining
6,7,1867,Saratoga Investama Sedaya,Jakarta,.12,1.7,4.3,3.4,Holding company